@startuml hiddlestick

!theme plain
skinparam ClassAttributeIconSize 0

class User{
    + ID : UUID
    + Handle : CHAR(31)
    + Name : VARCHAR(63)
    + Password : CHAR(128)
    + ProfilePicture : VARCHAR(255)
    + CreationTime : TIMESTAMP
}

class Post{
    + ID : UUID
    /'
    /+ CreatorID : UUID
    /+ StickerID : UUID
    '/
    + Media : VARCHAR(255)
    + Content : VARCHAR(1023)
    + CreationTime : TIMESTAMP
}

class Sticker{
    + ID : UUID
    + Name : CHAR(31)
    + Location : VARCHAR(255)
    /'
    /+ CreatorID : UUID
    '/
    + Description : VARCHAR(511)
    + CreationTime : TIMESTAMP
}

User "0..n" -- "0..n" User : aims at >
(User, User) . Shoot
User "1..1" -- "0..n" Post : creates >
User "1..1" -- "0..n" Sticker : creates >
Post "0..n" -- "1..1" Sticker : includes >
User "0..n" -- "0..n" Post : likes >
Session "1..n" -- "1..1" User : authenticates >
(User, Post) . Like

class Shoot{
    /'
    /+ Target : UUID
    /+ Archer : UUID
    '/
    + Shot : TIMESTAMP
}

class Like{
    /'
    /+ PostID : UUID
    /+ UserID : UUID
    '/
    + Time : TIMESTAMP
}

class Session{
    /'
    /+ UserID : UUID
    '/
    + CreationTime : TIMESTAMP
    + Name : VARCHAR(127)
    + Token : UUID
    + ExpirationDate : DATE
}

@enduml