@startuml hiddlestick

!theme plain
skinparam ClassAttributeIconSize 0

class User{
    + Handle : CHAR(31)
    + Name : VARCHAR(63)
    + Password : CHAR(128)
    + CreationTime : DATETIME
}

class Post{
    + ID : INTEGER
    /'
    + Creator : CHAR(31)
    + Sticker : CHAR(31)
    '/
    + Media : VARCHAR(255)
    + Content : VARCHAR(1023)
    + CreationTime : DATETIME
}

class Sticker{
    + Name : CHAR(31)
    + Location : VARCHAR(255)
    /'
    + Creator : CHAR(31)
    '/
    + Description : VARCHAR(511)
    + CreationTime : DATETIME
}

User "0..n" -- "0..n" User : aims at >
(User, User) . Shoot
User "1..1" -- "0..n" Post : creates >
User "1..1" -- "0..n" Sticker : creates >
Post "0..n" -- "1..1" Sticker : includes >
User "0..n" -- "0..n" Post : likes >
(User, Post) . Like

class Shoot{
    /'
    + Target : CHAR(31)
    + Archer : CHAR(31)
    '/
    + Shot : DATETIME
}

class Like{
    /'
    + PostID : INTEGER
    + User : CHAR(31)
    '/
    + Time : DATETIME
}

@enduml